language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20
script: python setup.py test
